### ISSUE TITLE
Gitbook content also in markdown? 

### ISSUE THREAD

**Issue by jurra** [UtrechtUniversity/workshop-computational-reproducibility#33]
Hi @bvreede. My name is Jose Urra, I am an RSE at TU Delft. 
I really liked the gitbook you have put together. I would also like to use the content to address FAIR enough research code practices. Do you happen to have also those in markdown?

I was wondering also why you decided to go for Gitbook, if people want to do pull requests to the content for instance I find it can be limiting. Did you consider using something like jupyter books?

**Comment by bvreede** [comment]
Thanks @jurra — actually, the one who made the book is @nehamoopen, and she's the current maintainer!

**Comment by nehamoopen** [comment]
Hi @jurra 👋 
Nice to hear that you like the format of our materials! 

Gitbook is something of a misnomer here. I built the book using the [bookdown](https://bookdown.org/yihui/bookdown/) package in R (and the specific style/theme used is Gitbook). bookdown uses R Markdown and the 'chapters' are all in the repository as Rmd files - so anyone can make a pull request as you describe. Working with bookdown is largely the same as with a Jupyter Book, albeit this is in R.

We've also rigged up a CI/CD pipeline using GitHub Actions so the book is rendered automatically when a pull request is merged. This means no one has to open up RStudio in order to edit the Rmd files and re-render the book. This was the basis for it: https://medium.com/@delucmat/how-to-publish-bookdown-projects-with-github-actions-on-github-pages-6e6aecc7331e

As for the course content itself, you're more than welcome to reuse it to address FAIR-enough research code practices. Drop us a link if you ever put your materials online!

**Comment by jurra** [comment]
Thank you @nehamoopen, I basically took all the material and remade it into a jupyter book so that it would be easier for us to add or tweak content. Nothing really changed in terms of contents. 

We are also planning to reuse it in our RSE as a kind of guides for researchers at TU Delft.
Great material! thanks again!
