### ISSUE TITLE
clean up + reorganize repo for Quarto

### ISSUE THREAD

**Issue by nehamoopen** [UtrechtUniversity/workshop-computational-reproducibility#35]
refer to the python workshop as a basis: https://github.com/UtrechtUniversity/workshop-introduction-to-python

keep the following structure:
- a `book` directory to contain all the Quarto book files
- a `docs` directory to contain the rendered Quarto book files in HTML
- a `slides` directory to contain _both_ the Rmd & HTML files for the slides
- eventually we can implement a GitHub Actions workflow to render the book, so the `docs` folder may become redundant - but let's make a start here.

test locally with a minimal example:

- make a branch of `main` and remove all the content except for `index.qmd` and one book chapter (perhaps `project setup`) and the corresponding slides...
- embedding slides could work with the following code chunk (example):

```{=html}
<iframe class="slide-deck" src="slides/index.html"></iframe>
```

**Comment by nehamoopen** [comment]
Figured it out! This code chunk works with Xaringan slides:

```{r embed-xaringan-1, echo=FALSE}
xaringanExtra::embed_xaringan(url = "../slides/slides_introduction.html", ratio = "4:3")
```

**Comment by DorienHuijser** [comment]
It's pushed to the `quarto-test` branch now. A few notes:

- "book" directory is called "bookfiles" instead. I got a weird build error with the name "book"
- the slides refer to the correct htmls but they still lost their formatting somehow. Couldn't quite figure out what exactly happened there
- I haven't checked if all the crosslinks within the book still work. There were some errors that images could not be found. This is probably because the "chapters" are now moved to a subfolder

In all, work in progress, but the basics seem to work :)
